// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu4tlJHJ8Hkmq7byKnbxda89EahiFfhvE',
    appId: '1:53062863542:web:1a9866e75f47f5dcf23417',
    messagingSenderId: '53062863542',
    projectId: 'mis-lab3-c73cd',
    authDomain: 'mis-lab3-c73cd.firebaseapp.com',
    storageBucket: 'mis-lab3-c73cd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk4Ch-GXd-tolMA5HTyiOoD-0otyJpOcM',
    appId: '1:53062863542:android:07501e2f0f8ed792f23417',
    messagingSenderId: '53062863542',
    projectId: 'mis-lab3-c73cd',
    storageBucket: 'mis-lab3-c73cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCImlR7EmRj2kv7_KjXHczlODEHyI_y3v8',
    appId: '1:53062863542:ios:860fa96d2c189fc9f23417',
    messagingSenderId: '53062863542',
    projectId: 'mis-lab3-c73cd',
    storageBucket: 'mis-lab3-c73cd.firebasestorage.app',
    iosBundleId: 'com.example.misLab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCImlR7EmRj2kv7_KjXHczlODEHyI_y3v8',
    appId: '1:53062863542:ios:860fa96d2c189fc9f23417',
    messagingSenderId: '53062863542',
    projectId: 'mis-lab3-c73cd',
    storageBucket: 'mis-lab3-c73cd.firebasestorage.app',
    iosBundleId: 'com.example.misLab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu4tlJHJ8Hkmq7byKnbxda89EahiFfhvE',
    appId: '1:53062863542:web:5e3b26e440164f35f23417',
    messagingSenderId: '53062863542',
    projectId: 'mis-lab3-c73cd',
    authDomain: 'mis-lab3-c73cd.firebaseapp.com',
    storageBucket: 'mis-lab3-c73cd.firebasestorage.app',
  );
}
